name: Build, Test, and Deploy NGINX Web Application

on:
  push:
    branches:
      - main # change to your main branch name if different
  pull_request:
    branches:
      - main # change to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the nginx application
      - name: Build nginx application
        run: |
          docker build -t nginx-webapp .
          
      # Test the application
      - name: Test application
        run: |
          docker run --rm nginx-webapp nginx -t

      # Deploy the application to Kubernetes
      - name: Deploy application
        uses: appleboy/kubectl-action@master
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          command: apply
          manifest: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml # change to your service manifest

